# Generated by Django 4.2 on 2023-08-24 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='SegundoApelldio',
            new_name='SegundoApellido',
        ),
    ]
